## IRIS CLASSIFICATION

In [35]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.tree import DecisionTreeClassifier
from sklearn import metrics
from sklearn import svm
from sklearn.model_selection import train_test_split

**Stage1:DataSourcing**

In [36]:
iris_Data=pd.read_csv('iris.csv')

In [37]:
iris_Data

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
0              5.1           3.5            1.4           0.2     Iris-setosa
1              4.9           3.0            1.4           0.2     Iris-setosa
2              4.7           3.2            1.3           0.2     Iris-setosa
3              4.6           3.1            1.5           0.2     Iris-setosa
4              5.0           3.6            1.4           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
145            6.7           3.0            5.2           2.3  Iris-virginica
146            6.3           2.5            5.0           1.9  Iris-virginica
147            6.5           3.0            5.2           2.0  Iris-virginica
148            6.2           3.4            5.4           2.3  Iris-virginica
149            5.9           3.0            5.1           1.8  Iris-virginica

[150 rows x 5 columns]

**Stage2:DataIngestion**

In [38]:
#Train_test_split
iris_Train,iris_Test=train_test_split(iris_Data,test_size=0.2,random_state=42)

**Train Data**

In [39]:
iris_Train

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm          Species
22             4.6           3.6            1.0           0.2      Iris-setosa
15             5.7           4.4            1.5           0.4      Iris-setosa
65             6.7           3.1            4.4           1.4  Iris-versicolor
11             4.8           3.4            1.6           0.2      Iris-setosa
42             4.4           3.2            1.3           0.2      Iris-setosa
..             ...           ...            ...           ...              ...
71             6.1           2.8            4.0           1.3  Iris-versicolor
106            4.9           2.5            4.5           1.7   Iris-virginica
14             5.8           4.0            1.2           0.2      Iris-setosa
92             5.8           2.6            4.0           1.2  Iris-versicolor
102            7.1           3.0            5.9           2.1   Iris-virginica

[120 rows x 5 columns]

**Test Data**

In [40]:
iris_Test

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm          Species
73             6.1           2.8            4.7           1.2  Iris-versicolor
18             5.7           3.8            1.7           0.3      Iris-setosa
118            7.7           2.6            6.9           2.3   Iris-virginica
78             6.0           2.9            4.5           1.5  Iris-versicolor
76             6.8           2.8            4.8           1.4  Iris-versicolor
31             5.4           3.4            1.5           0.4      Iris-setosa
64             5.6           2.9            3.6           1.3  Iris-versicolor
141            6.9           3.1            5.1           2.3   Iris-virginica
68             6.2           2.2            4.5           1.5  Iris-versicolor
82             5.8           2.7            3.9           1.2  Iris-versicolor
110            6.5           3.2            5.1           2.0   Iris-virginica
12             4.8           3.0            1.4           0.1      Iris-setosa
36             5.5           3.5            1.3           0.2      Iris-setosa
9              4.9           3.1            1.5           0.1      Iris-setosa
19             5.1           3.8            1.5           0.3      Iris-setosa
56             6.3           3.3            4.7           1.6  Iris-versicolor
104            6.5           3.0            5.8           2.2   Iris-virginica
69             5.6           2.5            3.9           1.1  Iris-versicolor
55             5.7           2.8            4.5           1.3  Iris-versicolor
132            6.4           2.8            5.6           2.2   Iris-virginica
29             4.7           3.2            1.6           0.2      Iris-setosa
127            6.1           3.0            4.9           1.8   Iris-virginica
26             5.0           3.4            1.6           0.4      Iris-setosa
128            6.4           2.8            5.6           2.1   Iris-virginica
131            7.9           3.8            6.4           2.0   Iris-virginica
145            6.7           3.0            5.2           2.3   Iris-virginica
108            6.7           2.5            5.8           1.8   Iris-virginica
143            6.8           3.2            5.9           2.3   Iris-virginica
45             4.8           3.0            1.4           0.3      Iris-setosa
30             4.8           3.1            1.6           0.2      Iris-setosa

**Stage3:DataTransformation**

- **EDA:Exploratory Data Analysis**

1. **Top 5 Rows**

In [41]:
iris_Data.head()

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.9           3.0            1.4           0.2  Iris-setosa
2            4.7           3.2            1.3           0.2  Iris-setosa
3            4.6           3.1            1.5           0.2  Iris-setosa
4            5.0           3.6            1.4           0.2  Iris-setosa

2. **Shape of Data-set**

In [42]:
iris_Data.shape

(150, 5)

3. **Data Types**

In [43]:
iris_Data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   SepalLengthCm  150 non-null    float64
 1   SepalWidthCm   150 non-null    float64
 2   PetalLengthCm  150 non-null    float64
 3   PetalWidthCm   150 non-null    float64
 4   Species        150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

**Insights: Float and Object type of data present**

4. **Stastics about Data**

In [44]:
iris_Data.describe()

       SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count     150.000000    150.000000     150.000000    150.000000
mean        5.843333      3.054000       3.758667      1.198667
std         0.828066      0.433594       1.764420      0.763161
min         4.300000      2.000000       1.000000      0.100000
25%         5.100000      2.800000       1.600000      0.300000
50%         5.800000      3.000000       4.350000      1.300000
75%         6.400000      3.300000       5.100000      1.800000
max         7.900000      4.400000       6.900000      2.500000

5. **Data Checks**

- Check for missing values

In [45]:
iris_Data.isna().sum()

SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

**Insight:No missing Values**

- **Check for Duplicated data**

In [46]:
iris_Data.duplicated().sum()

3

**Insights : 3 rows are duplicated**

In [79]:
new_iris_data=iris_Data.drop_duplicates()

In [80]:
new_iris_data

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
0              5.1           3.5            1.4           0.2     Iris-setosa
1              4.9           3.0            1.4           0.2     Iris-setosa
2              4.7           3.2            1.3           0.2     Iris-setosa
3              4.6           3.1            1.5           0.2     Iris-setosa
4              5.0           3.6            1.4           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
145            6.7           3.0            5.2           2.3  Iris-virginica
146            6.3           2.5            5.0           1.9  Iris-virginica
147            6.5           3.0            5.2           2.0  Iris-virginica
148            6.2           3.4            5.4           2.3  Iris-virginica
149            5.9           3.0            5.1           1.8  Iris-virginica

[147 rows x 5 columns]

In [81]:
new_iris_data.duplicated().sum()

0

**Insights: duplicate rows removed**

-**number of Unique values Each column**

In [54]:
new_iris_data.nunique()

SepalLengthCm    35
SepalWidthCm     23
PetalLengthCm    43
PetalWidthCm     22
Species           3
dtype: int64

- **Spliting numerical and categorical features**

In [60]:
Numerical_Features=[feature for feature in new_iris_data.columns if new_iris_data[feature].dtype!='object']
Categorical_Features=[feature for feature in new_iris_data.columns if new_iris_data[feature].dtype=='object']

**Numerical_Features**

In [61]:
Numerical_Features

['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm']

**Categorical_Features**

In [62]:
Categorical_Features

['Species']

In [69]:
new_iris_data

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0              5.1           3.5            1.4           0.2     [setosa]
1              4.9           3.0            1.4           0.2     [setosa]
2              4.7           3.2            1.3           0.2     [setosa]
3              4.6           3.1            1.5           0.2     [setosa]
4              5.0           3.6            1.4           0.2     [setosa]
..             ...           ...            ...           ...          ...
145            6.7           3.0            5.2           2.3  [virginica]
146            6.3           2.5            5.0           1.9  [virginica]
147            6.5           3.0            5.2           2.0  [virginica]
148            6.2           3.4            5.4           2.3  [virginica]
149            5.9           3.0            5.1           1.8  [virginica]

[147 rows x 5 columns]

**Stage4: Model Trainer**

In [82]:
#Train_test_split
Train,Test=train_test_split(new_iris_data,test_size=0.2,random_state=42)

In [83]:
Train

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm          Species
137            6.4           3.1            5.5           1.8   Iris-virginica
47             4.6           3.2            1.4           0.2      Iris-setosa
121            5.6           2.8            4.9           2.0   Iris-virginica
27             5.2           3.5            1.5           0.2      Iris-setosa
4              5.0           3.6            1.4           0.2      Iris-setosa
..             ...           ...            ...           ...              ...
73             6.1           2.8            4.7           1.2  Iris-versicolor
108            6.7           2.5            5.8           1.8   Iris-virginica
14             5.8           4.0            1.2           0.2      Iris-setosa
94             5.6           2.7            4.2           1.3  Iris-versicolor
104            6.5           3.0            5.8           2.2   Iris-virginica

[117 rows x 5 columns]

In [84]:
Test

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm          Species
127            6.1           3.0            4.9           1.8   Iris-virginica
53             5.5           2.3            4.0           1.3  Iris-versicolor
140            6.7           3.1            5.6           2.4   Iris-virginica
19             5.1           3.8            1.5           0.3      Iris-setosa
106            4.9           2.5            4.5           1.7   Iris-virginica
12             4.8           3.0            1.4           0.1      Iris-setosa
78             6.0           2.9            4.5           1.5  Iris-versicolor
31             5.4           3.4            1.5           0.4      Iris-setosa
83             6.0           2.7            5.1           1.6  Iris-versicolor
9              4.9           3.1            1.5           0.1      Iris-setosa
26             5.0           3.4            1.6           0.4      Iris-setosa
98             5.1           2.5            3.0           1.1  Iris-versicolor
146            6.3           2.5            5.0           1.9   Iris-virginica
69             5.6           2.5            3.9           1.1  Iris-versicolor
136            6.3           3.4            5.6           2.4   Iris-virginica
68             6.2           2.2            4.5           1.5  Iris-versicolor
18             5.7           3.8            1.7           0.3      Iris-setosa
71             6.1           2.8            4.0           1.3  Iris-versicolor
126            6.2           2.8            4.8           1.8   Iris-virginica
30             4.8           3.1            1.6           0.2      Iris-setosa
29             4.7           3.2            1.6           0.2      Iris-setosa
107            7.3           2.9            6.3           1.8   Iris-virginica
38             4.4           3.0            1.3           0.2      Iris-setosa
120            6.9           3.2            5.7           2.3   Iris-virginica
57             4.9           2.4            3.3           1.0  Iris-versicolor
22             4.6           3.6            1.0           0.2      Iris-setosa
66             5.6           3.0            4.5           1.5  Iris-versicolor
135            7.7           3.0            6.1           2.3   Iris-virginica
84             5.4           3.0            4.5           1.5  Iris-versicolor
11             4.8           3.4            1.6           0.2      Iris-setosa

In [86]:
Train_x=Train[['SepalLengthCm','SepalWidthCm','PetalLengthCm','PetalWidthCm']]
Train_y=Train[['Species']]

In [87]:
Train_x

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
137            6.4           3.1            5.5           1.8
47             4.6           3.2            1.4           0.2
121            5.6           2.8            4.9           2.0
27             5.2           3.5            1.5           0.2
4              5.0           3.6            1.4           0.2
..             ...           ...            ...           ...
73             6.1           2.8            4.7           1.2
108            6.7           2.5            5.8           1.8
14             5.8           4.0            1.2           0.2
94             5.6           2.7            4.2           1.3
104            6.5           3.0            5.8           2.2

[117 rows x 4 columns]

In [88]:
Train_y

             Species
137   Iris-virginica
47       Iris-setosa
121   Iris-virginica
27       Iris-setosa
4        Iris-setosa
..               ...
73   Iris-versicolor
108   Iris-virginica
14       Iris-setosa
94   Iris-versicolor
104   Iris-virginica

[117 rows x 1 columns]

In [89]:
Test_x=Test[['SepalLengthCm','SepalWidthCm','PetalLengthCm','PetalWidthCm']]
Test_y=Test[['Species']]

In [90]:
Test_x

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
127            6.1           3.0            4.9           1.8
53             5.5           2.3            4.0           1.3
140            6.7           3.1            5.6           2.4
19             5.1           3.8            1.5           0.3
106            4.9           2.5            4.5           1.7
12             4.8           3.0            1.4           0.1
78             6.0           2.9            4.5           1.5
31             5.4           3.4            1.5           0.4
83             6.0           2.7            5.1           1.6
9              4.9           3.1            1.5           0.1
26             5.0           3.4            1.6           0.4
98             5.1           2.5            3.0           1.1
146            6.3           2.5            5.0           1.9
69             5.6           2.5            3.9           1.1
136            6.3           3.4            5.6           2.4
68             6.2           2.2            4.5           1.5
18             5.7           3.8            1.7           0.3
71             6.1           2.8            4.0           1.3
126            6.2           2.8            4.8           1.8
30             4.8           3.1            1.6           0.2
29             4.7           3.2            1.6           0.2
107            7.3           2.9            6.3           1.8
38             4.4           3.0            1.3           0.2
120            6.9           3.2            5.7           2.3
57             4.9           2.4            3.3           1.0
22             4.6           3.6            1.0           0.2
66             5.6           3.0            4.5           1.5
135            7.7           3.0            6.1           2.3
84             5.4           3.0            4.5           1.5
11             4.8           3.4            1.6           0.2

In [91]:
Test_y

             Species
127   Iris-virginica
53   Iris-versicolor
140   Iris-virginica
19       Iris-setosa
106   Iris-virginica
12       Iris-setosa
78   Iris-versicolor
31       Iris-setosa
83   Iris-versicolor
9        Iris-setosa
26       Iris-setosa
98   Iris-versicolor
146   Iris-virginica
69   Iris-versicolor
136   Iris-virginica
68   Iris-versicolor
18       Iris-setosa
71   Iris-versicolor
126   Iris-virginica
30       Iris-setosa
29       Iris-setosa
107   Iris-virginica
38       Iris-setosa
120   Iris-virginica
57   Iris-versicolor
22       Iris-setosa
66   Iris-versicolor
135   Iris-virginica
84   Iris-versicolor
11       Iris-setosa

In [92]:
#SVM
model=svm.SVC()

In [93]:
#training model
model.fit(Train_x,Train_y)
pred=model.predict(Test_x)

E:\Anaconda\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [94]:
pred

array(['Iris-virginica', 'Iris-versicolor', 'Iris-virginica',
       'Iris-setosa', 'Iris-versicolor', 'Iris-setosa', 'Iris-versicolor',
       'Iris-setosa', 'Iris-virginica', 'Iris-setosa', 'Iris-setosa',
       'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-versicolor', 'Iris-virginica', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-versicolor',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa'], dtype=object)

In [95]:
metrics.accuracy_score(pred,Test_y)

0.9333333333333333

**Accuracy is 93% with svm**

In [96]:
#Decision Tree
model=DecisionTreeClassifier()

In [97]:
#training model
model.fit(Train_x,Train_y)
pred=model.predict(Test_x)

In [98]:
metrics.accuracy_score(pred,Test_y)

0.9333333333333333

**Accuracy is 93% with Decision Tree**